"""
Iota — Master Command Catalog (used by the /commands command).

Every command registered in bot.py is documented here with:
  • the category it belongs to
  • a short, human-readable USE CASE (what it's for)

This is the single source of truth for /commands. If a command is ever
added but not documented below, /commands falls back to a safe generic
description so the listing can never crash.
"""
from collections import OrderedDict

# command -> [category, use_case]
CATALOG = {
    # ── Fun / Actions ────────────────────────────────────────────────
    "slap": ["Fun", "Slap someone with a funny animated reaction."],
    "punch": ["Fun", "Punch a friend in a playful way."],
    "kiss": ["Fun", "Send a kiss to someone."],
    "hug": ["Fun", "Hug a user virtually."],
    "bite": ["Fun", "Bite someone playfully."],
    "pat": ["Fun", "Pat someone on the head."],
    "cuddle": ["Fun", "Cuddle with a friend."],
    "lick": ["Fun", "Lick someone jokingly."],
    "bonk": ["Fun", "Bonk a user on the head."],
    "glare": ["Fun", "Give someone a deadly glare."],
    "feed": ["Fun", "Feed a friend some food."],
    "beer": ["Fun", "Share a beer with someone."],
    "cry": ["Fun", "Cry dramatically (reaction emoji/sticker)."],
    "blush": ["Fun", "Blush at something."],
    "wave": ["Fun", "Wave hello to the chat."],
    "wink": ["Fun", "Wink at someone."],
    "dance": ["Fun", "Show off a dance."],
    "sleep": ["Fun", "Pretend to sleep."],
    "simp": ["Fun", "Call someone a simp (joke)."],
    "sus": ["Fun", "Mark someone as suspicious (among us style)."],
    "poke": ["Fun", "Poke a user."],
    "tickle": ["Fun", "Tickle someone."],
    "facepalm": ["Fun", "Facepalm at something silly."],
    "pie": ["Fun", "Throw a pie at someone."],
    "trip": ["Fun", "Trip a user over."],
    "freeze": ["Fun", "Freeze someone in place."],
    "zap": ["Fun", "Zap a user with lightning."],
    "dancewith": ["Fun", "Dance together with someone."],
    "highfive": ["Fun", "Give a high five."],
    "throw": ["Fun", "Throw something at a user."],
    "fall": ["Fun", "Fall down comically."],
    "kick": ["Fun", "Kick someone (fun variant)."],
    "murder": ["Fun", "Fake-murder someone for laughs."],
    "stupid_meter": ["Fun", "Rate how stupid a user is (joke %)."],
    "brain": ["Fun", "Show your big brain energy."],
    "look": ["Fun", "Look at someone/something."],
    "ship": ["Fun", "Ship two users as a couple."],
    "compliment": ["Fun", "Give someone a random compliment."],
    "roast": ["Fun", "Roast a user with a joke insult."],
    "horoscope": ["Fun", "Get a fun horoscope reading."],
    "shayari": ["Fun", "Send a poetic shayari line."],
    "meme": ["Fun", "Generate/post a meme."],
    "work": ["Fun", "Do a fake work shift for coins."],
    "story": ["Fun", "Tell a short random story."],
    "whatif": ["Fun", "Answer a 'what if' scenario."],
    "settitle": ["Fun", "Set your custom fanciable title."],
    "top": ["Fun", "Show the top something (leaderboard flavour)."],
    "hot": ["Fun", "Rate how hot someone is (joke)."],
    "rate": ["Fun", "Rate a user out of 10."],
    "nhie": ["Fun", "Play 'Never Have I Ever'."],
    "judge": ["Fun", "Judge a user's profile pic."],
    "roastme": ["Fun", "Ask the bot to roast you."],
    "advice": ["Fun", "Get a random piece of advice."],
    "aistory": ["Fun", "Make the AI tell a short story."],
    "aijoke": ["Fun", "Get an AI-generated joke."],
    "joke": ["Fun", "Tell a random joke."],
    "fact": ["Fun", "Share a random fun fact."],
    "riddle": ["Fun", "Pose a riddle to the chat."],
    "wyr": ["Fun", "Play 'Would You Rather'."],
    "truth": ["Fun", "Truth question (truth or dare)."],
    "dare": ["Fun", "Dare challenge (truth or dare)."],
    "puzzle": ["Fun", "Solve a word/number puzzle."],
    "simp": ["Fun", "Call someone a simp."],
    "brain": ["Fun", "Big brain energy."],

    # ── Romance / Social ──────────────────────────────────────────────
    "marry": ["Romance", "Propose/marry another user."],
    "divorce": ["Romance", "End your in-bot marriage."],
    "love": ["Romance", "Confess love to someone."],
    "crush": ["Romance", "Set your crush on someone."],
    "couples": ["Romance", "View couples in the chat."],
    "couple": ["Romance", "Make a couple profile."],
    "valentine": ["Romance", "Send a valentine to someone."],
    "valentine_cancel": ["Romance", "Cancel a sent valentine."],
    "valentine_stats": ["Romance", "See valentine event stats."],
    "valentine_delete": ["Romance", "Delete your valentine data."],
    "profile": ["Romance", "View your/someone's profile."],
    "bio": ["Romance", "Set your bio line."],

    # ── Economy ──────────────────────────────────────────────────────
    "bal": ["Economy", "Check your coin balance."],
    "wallet": ["Economy", "Check your protected wallet."],
    "daily": ["Economy", "Claim your daily coins."],
    "weekly": ["Economy", "Claim weekly coins (bigger)."],
    "monthly": ["Economy", "Claim monthly coins (biggest)."],
    "rob": ["Economy", "Rob another user's coins."],
    "kill": ["Economy", "Battle/kill a user for rewards."],
    "gkill": ["Economy", "Group kill event."],
    "grob": ["Economy", "Group rob event."],
    "gbal": ["Economy", "Group total balance."],
    "bank": ["Economy", "Open/use your bank account."],
    "deposit": ["Economy", "Deposit coins into the bank."],
    "withdraw": ["Economy", "Withdraw coins from the bank."],
    "loan": ["Economy", "Take a loan from the bank."],
    "repay": ["Economy", "Repay your bank loan."],
    "savings": ["Economy", "View bank savings + interest."],
    "networth": ["Economy", "See your total net worth."],
    "transfer": ["Economy", "(banking) transfer coins to a user."],
    "give": ["Economy", "Give coins to another user."],
    "pay": ["Economy", "Buy Iota Premium with coins."],
    "fpay": ["Economy", "Buy Premium with Telegram Stars."],
    "fgems": ["Economy", "Buy gems with Telegram Stars."],
    "buygem": ["Economy", "Buy gems with coins."],
    "gems": ["Economy", "Check your gem balance."],
    "gems2coins": ["Economy", "Convert gems back to coins."],
    "gemstore": ["Economy", "Open the gem store."],
    "coupon": ["Economy", "Redeem a coupon code."],
    "coupons": ["Economy", "List your redeemed coupons."],
    "create_coupon": ["Economy", "Create a coupon (staff)."],
    "del_coupon": ["Economy", "Delete a coupon (staff)."],
    "economy": ["Economy", "Economy overview / help."],
    "protect": ["Economy", "Buy death protection."],
    "gprotect": ["Economy", "Group death protection."],
    "heal": ["Economy", "Heal after being killed."],
    "revive": ["Economy", "Revive yourself."],
    "grevive": ["Economy", "Group revive."],
    "register": ["Economy", "Register for the economy."],
    "rank": ["Economy", "See your economy rank."],
    "topkill": ["Economy", "Top killers leaderboard."],
    "streak": ["Economy", "View your daily streak."],
    "claim": ["Economy", "Claim a group reward."],

    # ── Premium ──────────────────────────────────────────────────────
    "check": ["Premium", "Check your premium/protection status privately."],
    "setemoji": ["Premium", "Set your custom premium emoji."],

    # ── Games ────────────────────────────────────────────────────────
    "chess": ["Games", "Play chess with another user."],
    "uno": ["Games", "Play a game of UNO."],
    "ludo": ["Games", "Play Ludo (mini-app)."],
    "tictactoe": ["Games", "Play tic-tac-toe."],
    "rps": ["Games", "Rock paper scissors."],
    "dice": ["Games", "Roll a dice."],
    "coinflip": ["Games", "Flip a coin."],
    "roll": ["Games", "Roll a random number."],
    "card": ["Games", "Play the card betting game."],
    "bluff": ["Games", "Play the bluff card game."],
    "bluffend": ["Games", "End a bluff game."],
    "hangman": ["Games", "Play hangman."],
    "quiz": ["Games", "Start a quiz."],
    "trivia": ["Games", "Answer trivia questions."],
    "werewolf": ["Games", "Play Werewolf."],
    "wwend": ["Games", "End a Werewolf game."],
    "connect4": ["Games", "Play Connect Four."],
    "tournament": ["Games", "Start a card tournament."],
    "guess": ["Games", "Number guessing game."],
    "wordgame": ["Games", "Word guessing game."],
    "bomb": ["Games", "Mines/bomb clicking game."],
    "prowl": ["Games", "Prowl game action."],
    "hack": ["Games", "Play Hack-the-Code."],
    "poll": ["Games", "Create a quick poll."],
    "vote": ["Games", "Vote in a poll/game."],
    "game": ["Games", "Open the games menu."],
    "games": ["Games", "List available games."],
    "bet": ["Games", "Place a bet."],
    "drop": ["Games", "Drop game action."],
    "flip": ["Games", "Flip game action."],
    "close": ["Games", "Close a game lobby."],
    "end": ["Games", "End the current game."],
    "enter": ["Games", "Enter a game/tournament."],
    "join": ["Games", "Join a game lobby."],
    "open": ["Games", "Open a game."],
    "myhand": ["Games", "Show your current hand."],
    "status": ["Games", "Show game status."],

    # ── Group Admin ──────────────────────────────────────────────────
    "warn": ["Group Admin", "Warn a member (admin/dot command)."],
    "unwarn": ["Group Admin", "Remove a warning."],
    "warns": ["Group Admin", "Show a user's warnings."],
    "resetallwarns": ["Group Admin", "Reset all warnings in a group."],
    "warnlimit": ["Group Admin", "Set the warn limit."],
    "setwarnlimit": ["Group Admin", "Set max warnings before action."],
    "setwarnmode": ["Group Admin", "Set warn action (ban/mute/kick)."],
    "ban": ["Group Admin", "Ban a member (dot/admin)."],
    "unban": ["Group Admin", "Unban a member."],
    "mute": ["Group Admin", "Mute a member."],
    "unmute": ["Group Admin", "Unmute a member."],
    "kick": ["Group Admin", "Kick a member from the group."],
    "promote": ["Group Admin", "Promote a member to admin."],
    "demote": ["Group Admin", "Demote an admin."],
    "lock": ["Group Admin", "Lock a permission in the group."],
    "unlock": ["Group Admin", "Unlock a permission."],
    "locks": ["Group Admin", "Show current locks."],
    "setflood": ["Group Admin", "Set the flood-control limit."],
    "floodmode": ["Group Admin", "Set flood action (mute/ban/kick)."],
    "rules": ["Group Admin", "Show the group rules."],
    "setrules": ["Group Admin", "Set the group rules."],
    "clearrules": ["Group Admin", "Clear the group rules."],
    "setwelcome": ["Group Admin", "Configure the welcome message."],
    "setgoodbye": ["Group Admin", "Set the goodbye message."],
    "setlang": ["Group Admin", "Set the group language."],
    "captcha": ["Group Admin", "Toggle join captcha."],
    "cleanservice": ["Group Admin", "Clean service/join messages."],
    "antichannelpin": ["Group Admin", "Block channels from pinning."],
    "disable": ["Group Admin", "Disable a command in the group."],
    "enable": ["Group Admin", "Enable a command in the group."],
    "disabled": ["Group Admin", "List disabled commands."],
    "silentactions": ["Group Admin", "Toggle silent moderation."],
    "admincache": ["Group Admin", "Refresh the admin cache."],
    "approve": ["Group Admin", "Approve a user (whitelist from locks)."],
    "unapprove": ["Group Admin", "Remove approval."],
    "approved": ["Group Admin", "List approved users."],
    "logchannel": ["Group Admin", "Set the group log channel."],
    "nolog": ["Group Admin", "Stop logging to the channel."],
    "prot": ["Group Admin", "Group protection settings."],
    "report": ["Group Admin", "Report a message to admins."],
    "reports": ["Group Admin", "View reported messages."],
    "addword": ["Group Admin", "Add a blacklist word."],
    "removeword": ["Group Admin", "Remove a blacklist word."],
    "badwords": ["Group Admin", "List blacklist words."],
    "del": ["Group Admin", "Delete replied-to messages."],
    "purge": ["Group Admin", "Purge multiple messages."],
    "pin": ["Group Admin", "Pin a message."],
    "unpin": ["Group Admin", "Unpin a message."],
    "slowmode": ["Group Admin", "Set group slow mode."],

    # ── Group Tools ──────────────────────────────────────────────────
    "setgtitle": ["Group Tools", "Change the group title."],
    "setgdesc": ["Group Tools", "Change the group description."],
    "setgpic": ["Group Tools", "Change the group photo."],
    "invitelink": ["Group Tools", "Get/show the invite link."],
    "revoke": ["Group Tools", "Revoke the invite link."],
    "chathistory": ["Group Tools", "Fetch group chat history."],
    "settag": ["Group Tools", "Set a group tag."],
    "deltag": ["Group Tools", "Delete a group tag."],
    "mytag": ["Group Tools", "Show your tag."],
    "tag": ["Group Tools", "Tag a group/role."],
    "link": ["Group Tools", "Save a group link."],
    "del_link": ["Group Tools", "Delete a saved link."],
    "setgroup": ["Group Tools", "Link your account to a group."],
    "removegroup": ["Group Tools", "Remove a group from your top groups (rank 1-5)."],
    "topgroups": ["Group Tools", "Top groups by activity."],
    "last_seen": ["Group Tools", "See when a user was last seen."],

    # ── GBAN / Fed ───────────────────────────────────────────────────
    "gban": ["Anti-Abuse", "Globally ban a user across all groups."],
    "ungban": ["Anti-Abuse", "Remove a global ban."],
    "gbanlist": ["Anti-Abuse", "List globally banned users."],
    "gcheck": ["Anti-Abuse", "Check a user's global-ban status."],

    # ── Utility ──────────────────────────────────────────────────────
    "tr": ["Utility", "Translate text to another language."],
    "id": ["Utility", "Show user/chat id info."],
    "chatid": ["Utility", "Show the current chat id."],
    "ocr": ["Utility", "Read text from an image."],
    "weather": ["Utility", "Get the weather for a city."],
    "wiki": ["Utility", "Search Wikipedia."],
    "calc": ["Utility", "Calculate a math expression."],
    "time": ["Utility", "Show the current time."],
    "currency": ["Utility", "Convert between currencies."],
    "define": ["Utility", "Define a word."],
    "short": ["Utility", "Shorten a URL."],
    "ping": ["Utility", "Check bot latency."],
    "uptime": ["Utility", "Show bot uptime."],
    "gstats": ["Utility", "Global bot statistics."],
    "adminlist": ["Utility", "List group admins."],
    "admins": ["Utility", "Show group admins."],
    "owner": ["Utility", "Show the bot owner."],
    "own": ["Utility", "Owner info command."],
    "ai": ["Utility", "Chat with the AI."],
    "ask": ["Utility", "Ask the AI a question."],
    "clearmemory": ["Utility", "Clear your AI chat memory."],
    "voice": ["Utility", "Text-to-speech a message."],
    "detail": ["Utility", "Full detail/lookup of a user."],
    "pfp": ["Utility", "Get a user's profile picture."],
    "remindme": ["Utility", "Set a personal reminder."],
    "schedule": ["Utility", "Schedule a reminder."],
    "sticky": ["Utility", "Make a sticky group message."],
    "rss": ["Utility", "Subscribe to an RSS feed."],
    "feedback": ["Utility", "Send feedback to the owner."],
    "afk": ["Utility", "Set yourself away-from-keyboard."],
    "todo": ["Utility", "Manage your to-do list."],
    "countdown": ["Utility", "Create a countdown."],
    "binary": ["Utility", "Convert text to binary."],
    "morse": ["Utility", "Convert text to Morse code."],
    "reverse": ["Utility", "Reverse a string."],
    "mock": ["Utility", "MoCk ThE tExT like this."],
    "hash": ["Utility", "Hash a string."],
    "password": ["Utility", "Generate a strong password."],
    "bubble": ["Utility", "Bubble-ify text."],
    "vapor": ["Utility", "Vaporwave-style text."],
    "uwu": ["Utility", "UwU-ify text."],
    "zalgo": ["Utility", "Zalgo-ify text."],
    "leet": ["Utility", "Leet-speak text."],
    "regional": ["Utility", "Regional-indicator text."],
    "clap": ["Utility", "Add 👏 between words."],
    "pick": ["Utility", "Pick one option randomly."],
    "rand": ["Utility", "Random choice/number."],
    "peek": ["Utility", "Peek into a chat."],

    # ── Stickers / Media ────────────────────────────────────────────
    "addsticker": ["Owner Systems", "Add a single sticker to a pack."],
    "addstickerpack": ["Stickers", "Save a whole sticker pack."],
    "addpack": ["Stickers", "Auto-save the replied sticker pack."],
    "stickerpacks": ["Stickers", "List saved sticker packs."],
    "previewsticker": ["Owner Systems", "Preview a mood's stickers."],
    "clearstickers": ["Stickers", "Wipe a sticker mood."],
    "setemoji": ["Stickers", "Set custom premium emoji."],

    # ── Items / Shop ────────────────────────────────────────────────
    "items": ["Items", "List available gift items."],
    "item": ["Items", "View a single item."],
    "shop": ["Items", "Open the shop."],
    "gift": ["Items", "Gift an item to someone."],
    "stash": ["Items", "Stash an item."],
    "mystash": ["Items", "View your stashed items."],

    # ── Village / War ───────────────────────────────────────────────
    "village": ["Village", "Open your village."],
    "collect": ["Village", "Collect village resources."],
    "storage": ["Village", "View village storage."],
    "vault": ["Village", "Open the village vault."],
    "mines": ["Village", "Work the mines."],
    "build": ["Village", "Build/upgrade a building."],
    "walls": ["Village", "Upgrade your walls."],
    "defense": ["Village", "Build defenses."],
    "train": ["Village", "Train troops."],
    "troops": ["Village", "View your troops."],
    "kingdom": ["Village", "View your kingdom."],
    "spy": ["Village", "Spy on an enemy village."],
    "attack": ["Village", "Attack another village."],
    "emperors": ["Village", "Top emperors leaderboard."],
    "settle": ["Village", "Settle a new village."],
    "convert": ["Village", "Convert resources."],
    "guide": ["Village", "Village gameplay guide."],
    "market": ["Village", "Village market."],

    # ── Tracking / Stats ────────────────────────────────────────────
    "stats": ["Stats", "Your or global stats."],
    "leaders": ["Stats", "Leaderboard."],
    "gleaders": ["Stats", "Global leaderboard."],
    "granks": ["Stats", "Global ranks."],
    "global_rank": ["Stats", "Your global rank."],
    "rank": ["Stats", "Your rank."],
    "top": ["Stats", "Top list."],
    "growth": ["Owner Systems", "Bot user-growth analytics."],
    "retention": ["Stats", "User retention analytics."],
    "latency": ["Stats", "Telegram API latency."],
    "health": ["Owner Systems", "Full system health check."],
    "pingall": ["Stats", "Ping all groups."],
    "deadgroups": ["Stats", "List inactive groups."],
    "online": ["Owner Systems", "Users active recently."],
    "commandstats": ["Stats", "Most-used commands."],
    "errorlog": ["Stats", "Recent bot errors."],
    "botstats": ["Owner Systems", "Bot-wide statistics."],
    "starsstats": ["Stats", "Telegram Stars earnings."],
    "economystats": ["Stats", "Economy overview."],
    "toprich": ["Stats", "Richest users."],

    # ── Info / Lookup ───────────────────────────────────────────────
    "detail": ["Info", "Deep user detail/history lookup."],
    "profile": ["Info", "Show a user profile."],
    "pfp": ["Info", "User profile picture."],
    "whereis": ["Info", "Find which groups a user is in."],
    "common": ["Info", "Common groups between two users."],
    "scan": ["Info", "Full user scan (owner)."],
    "userinfo": ["Owner Systems", "User info (owner)."],
    "userslist": ["Info", "List all users (owner)."],
    "premiumlist": ["Info", "List premium users (owner)."],

    # ── Owner Panel (existing) ──────────────────────────────────────
    "panel": ["Owner", "Open the owner control panel."],
    "ownersys": ["Owner", "New owner-systems command index."],
    "addcoins": ["Owner", "Add coins to a user."],
    "removecoins": ["Owner", "Remove coins from a user."],
    "addgems": ["Owner", "Add gems to a user."],
    "addpremium": ["Owner", "Grant premium to a user."],
    "removepremium": ["Owner", "Remove premium from a user."],
    "broadcast": ["Owner", "Broadcast to users/groups."],
    "forward": ["Owner", "Forward a message to all."],
    "addcoupon": ["Owner", "Create a coupon code."],
    "delcoupon": ["Owner", "Delete a coupon code."],
    "banuser": ["Owner", "Ban a user globally."],
    "unbanuser": ["Owner", "Unban a user."],
    "dm": ["Owner", "DM a user as the bot."],
    "setmodel": ["Owner", "Set the AI model."],
    "listmodels": ["Owner", "List AI models."],
    "refreshmodels": ["Owner", "Refresh AI model list."],
    "setmaxtokens": ["Owner", "Set max AI tokens."],
    "addapikey": ["Owner", "Add an AI provider key."],
    "removeapikey": ["Owner", "Remove an AI key."],
    "keypoolstatus": ["Owner", "Show AI key health."],
    "providerstatus": ["Owner", "Show AI provider status."],
    "setpriority": ["Owner", "Set AI provider priority."],
    "toggleprovider": ["Owner", "Toggle an AI provider."],
    "scan": ["Owner", "Deep-scan a user."],
    "resetuser": ["Owner", "Reset a user's data."],
    "giveall": ["Owner", "Give coins to all users."],
    "maintenance": ["Owner", "Toggle maintenance mode."],
    "premiumgiveaway": ["Owner", "Run a premium giveaway."],
    "ttssettings": ["Owner", "Configure TTS."],
    "previewtts": ["Owner", "Preview a TTS voice."],
    "ttsvoices": ["Owner", "List TTS voices."],
    "ttsrefresh": ["Owner", "Refresh TTS voices."],
    "clonevoice": ["Owner", "Clone a voice."],
    "clonedvoices": ["Owner", "List cloned voices."],
    "delclone": ["Owner", "Delete a cloned voice."],
    "addclone": ["Owner", "Register a cloned voice id."],
    "delbroadcast": ["Owner", "Delete a past broadcast."],
    "broadcasthistory": ["Owner", "Show broadcast history."],
    "globalclose": ["Owner", "Close the bot globally."],
    "globalopen": ["Owner", "Open the bot globally."],
    "leavegroup": ["Owner", "Leave a group."],
    "leaveallgroups": ["Owner", "Leave all groups."],
    "groupslist": ["Owner", "List all groups."],
    "groupscount": ["Owner", "Count tracked groups."],
    "chatinfo": ["Owner", "Info about a chat."],
    "antispam": ["Owner", "Toggle anti-spam."],
    "cleandb": ["Owner", "Clean the database."],
    "exportusers": ["Owner", "Export users."],
    "getfile": ["Owner", "Get a file from the bot."],
    "botinfo": ["Owner", "Bot information."],
    "sysinfo": ["Owner", "System information."],
    "logs": ["Owner", "View bot logs."],
    "restart": ["Owner", "Restart the bot."],
    "setbotname": ["Owner", "Set the bot's name."],
    "setbotdesc": ["Owner", "Set the bot's description."],
    "setbotpic": ["Owner", "Set the bot's picture."],
    "setbotcommands": ["Owner", "Set the bot command menu."],
    "setrules": ["Owner", "Set group rules (owner shortcut)."],

    # ── Owner Systems (NEW) ─────────────────────────────────────────
    "lockdown": ["Owner Systems", "Globally lock all groups."],
    "unlock": ["Owner Systems", "Release global lockdown."],
    "slowall": ["Owner Systems", "Slowmode in all groups."],
    "lockall": ["Owner Systems", "Lock media in all groups."],
    "unlockall": ["Owner Systems", "Unlock media in all groups."],
    "shieldstatus": ["Owner Systems", "Show shield status."],
    "massban": ["Owner Systems", "Ban users from every group."],
    "massunban": ["Owner Systems", "Unban users everywhere."],
    "banfrom": ["Owner Systems", "Ban a user from one group."],
    "unbanfrom": ["Owner Systems", "Unban from one group."],
    "cleanbots": ["Owner Systems", "Kick bots from a group."],
    "botgate": ["Owner Systems", "Bot-gate policy control."],
    "allowedbots": ["Owner Systems", "Bot-gate allowlist."],
    "watchuser": ["Owner Systems", "Watch a user's activity."],
    "unwatch": ["Owner Systems", "Stop watching a user."],
    "watchlist": ["Owner Systems", "List watched users."],
    "suslist": ["Owner Systems", "List suspicious new accounts."],
    "schedbroadcast": ["Owner Systems", "Schedule a broadcast."],
    "schedmsg": ["Owner Systems", "Schedule a group message."],
    "remindall": ["Owner Systems", "Schedule msg to all groups."],
    "scheds": ["Owner Systems", "List scheduled jobs."],
    "cancelsched": ["Owner Systems", "Cancel a scheduled job."],
    "autoreply": ["Owner Systems", "Add a global auto-reply."],
    "autoreplies": ["Owner Systems", "List auto-replies."],
    "delautoreply": ["Owner Systems", "Delete an auto-reply."],
    "blackword": ["Owner Systems", "Add a global blacklist word."],
    "blackwords": ["Owner Systems", "List blacklist words."],
    "delblackword": ["Owner Systems", "Remove a blacklist word."],
    "sudoadd": ["Owner Systems", "Add sudo staff."],
    "sudoremove": ["Owner Systems", "Remove sudo staff."],
    "stafflist": ["Owner Systems", "List staff."],
    "handover": ["Owner Systems", "Transfer ownership."],
    "economystats": ["Owner Systems", "Economy overview."],
    "rain": ["Owner Systems", "Rain coins to users."],
    "reseteco": ["Owner Systems", "Reset a user's economy."],
    "dbstats": ["Owner Systems", "Database statistics."],
    "exportcsv": ["Owner Systems", "Export users to CSV."],
    "backup": ["Owner Systems", "Backup the database."],
    "vacuum": ["Owner Systems", "Clean up old jobs/logs."],
    "indexes": ["Owner Systems", "Ensure DB indexes."],
    "persona": ["Owner Systems", "Set the bot persona."],
    "defaultwelcome": ["Owner Systems", "Set a global default welcome."],
    "forcewelcome": ["Owner Systems", "Force-enable welcome everywhere."],
    "botbio": ["Owner Systems", "Set the bot bio."],
    "setmenu": ["Owner Systems", "Set the menu button URL."],
    "logchat": ["Owner Systems", "Set the log channel."],
    "notify": ["Owner Systems", "Toggle owner notifications."],
    "alert": ["Owner Systems", "Send an owner alert."],
    "osetrules": ["Owner Systems", "Owner: set a group's rules by chat_id."],
    "osetbotname": ["Owner Systems", "Owner: set the bot's display name."],
    "opurge": ["Owner Systems", "Owner: purge N messages in any group."],

    # ── Premium Banking (real-life style) ─────────────────────────────
    "bank": ["Premium Banking", "Your bank account (safe from /rob) + overview."],
    "deposit": ["Premium Banking", "Move coins wallet → bank."],
    "withdraw": ["Premium Banking", "Move coins bank → wallet."],
    "loan": ["Premium Banking", "Borrow coins (interest, due in 24h)."],
    "repay": ["Premium Banking", "Repay an outstanding loan."],
    "transfer": ["Premium Banking", "Send coins to another user."],
    "savings": ["Premium Banking", "Interest-bearing savings vault (2%/day)."],
    "networth": ["Premium Banking", "Total wealth (wallet+bank+savings−loan)."],
    "fd": ["Premium Banking", "Fixed Deposit: lock coins, earn higher interest."],
    "rd": ["Premium Banking", "Recurring Deposit: monthly installments + interest."],
    "statement": ["Premium Banking", "Passbook: recent transactions."],
    "openbank": ["Premium Banking", "Open your own Bank/Branch (need 10 lakh)."],
    "mybank": ["Premium Banking", "Manage your owned bank."],
    "bankinfo": ["Premium Banking", "View a bank's public info."],
    "banks": ["Premium Banking", "List Iota's Banks/Branches."],
    "bankdeposit": ["Premium Banking", "Deposit coins into a user-owned bank."],
    "bankwithdraw": ["Premium Banking", "Withdraw from a user-owned bank."],
    "setbankname": ["Premium Banking", "Rename your bank."],
    "setbankrate": ["Premium Banking", "Set your bank's customer interest rate."],
    "closebank": ["Premium Banking", "Close your bank (returns all deposits)."],

    # ── Premium Business Empire (Enterprise) ─────────────────────────
    "business": ["Business", "Your business overview (till, staff, investors, popularity, rating)."],
    "openbusiness": ["Business", "Open a business (Premium + cost + license fee; tier & global-limit gated)."],
    "bizcollect": ["Business", "Collect income (tax + maintenance deducted, investor dividends paid)."],
    "bizupgrade": ["Business", "Upgrade your business (more income / bigger till / higher valuation)."],
    "bizinfo": ["Business", "View any business's public info (incl. limited-status)."],
    "businesses": ["Business", "Leaderboard of Iota's top businesses by valuation."],
    "hire": ["Business", "Offer a user a staff job (role bonuses + skill)."],
    "bizfire": ["Business", "Fire an employee."],
    "bizjob": ["Business", "View the job you're employed in (level, efficiency, earnings)."],
    "bizquit": ["Business", "Quit your job."],
    "bizinvest": ["Business", "Invest coins to become a shareholder (dividends + income bonus)."],
    "bizdivest": ["Business", "Pull your investment out (early-exit fee)."],
    "bizinvestments": ["Business", "Your active investments / dividends."],
    "robbiz": ["Business", "Rob a business's uncollected till (Premium; guards reduce take)."],
    "bizrename": ["Business", "Rename your business."],
    "bizclose": ["Business", "Close your business (refunds till + investors)."],
    "biztypes": ["Business", "Browse all business types, costs, license fees & global limits."],
    "bizstats": ["Business", "Analytics dashboard: revenue, expenses, profit, rating, valuation."],
    "bizemployees": ["Business", "List your employees with level / efficiency / earnings."],
    "bizpromote": ["Business", "Promote an employee (costs a fee; raises efficiency)."],
    "bizdemote": ["Business", "Demote an employee (lowers efficiency)."],
    "bizbonus": ["Business", "Give an employee a one-off bonus from your wallet."],
    "bizpenalty": ["Business", "Penalise an employee (hits efficiency & mood)."],
    "bizrate": ["Business", "Leave a 1–5★ customer rating for a business."],
    "bizselect": ["Business", "Switch your active business (if you own several)."],

    # ── Misc ────────────────────────────────────────────────────────
    "start": ["Core", "Start / welcome message."],
    "help": ["Core", "Show help / command guide."],
    "commands": ["Core", "Full command catalog (this)."],
    "payment": ["Core", "Alias for premium purchase (DM only)."],
    "terms": ["Legal", "Terms of service."],
    "refund": ["Legal", "Refund policy."],
    "policy": ["Legal", "Privacy/rules policy."],
    "rules": ["Group Admin", "Show group rules."],
    "donate": ["Misc", "Donate to support the bot."],
    "repair": ["Misc", "Repair command (owner utility)."],
    "raidlog": ["Misc", "Raid log (owner)."],
    "recruit": ["Misc", "Recruit command."],
    "connect": ["Misc", "Connect feature."],
    "disconnect": ["Misc", "Disconnect feature."],
    "connect_id": ["Misc", "Connect by id."],
    "whisper": ["Misc", "Send a private whisper."],
    "confession": ["Misc", "Anonymous confession."],
    "judge": ["Fun", "Judge a profile pic."],
    "promoter": ["Misc", "Get your referral link."],
    "ref_stats": ["Misc", "Your referral earnings."],
    "freeze": ["Fun", "Freeze someone."],
    "sus": ["Fun", "Sus someone."],
}

# Friendly display order for categories in the /commands menu.
CATEGORY_ORDER = [
    "Core", "Fun", "Romance", "Economy", "Premium", "Premium Banking", "Business",
    "Games",
    "Group Admin", "Group Tools", "Anti-Abuse", "Utility", "Stickers", "Items",
    "Village", "Stats", "Info", "Owner", "Owner Systems", "Legal", "Misc",
]


def get_category(cmd: str) -> str:
    return CATALOG.get(cmd, ["Misc", ""])[0]


# Owner/staff-only commands that live INSIDE otherwise-public categories
# (e.g. "userslist"/"premiumlist" live in "Info"). They must be hidden from
# the public /commands catalog — the command still executes, but only the
# owner can actually run it. OWNER_ONLY_CATS hides whole categories; this
# list hides individual owner commands that leak into public categories.
OWNER_ONLY_CMDS = {
    "userslist", "premiumlist", "own", "raidlog", "repair", "scan",
}


def is_owner_only(cmd: str) -> bool:
    return cmd in OWNER_ONLY_CMDS


def get_usecase(cmd: str) -> str:
    entry = CATALOG.get(cmd)
    if entry:
        return entry[1]
    return "Iota feature command."


def all_categories() -> "OrderedDict[str, list]":
    """Return categories (in display order) -> list of (cmd, usecase)."""
    out = OrderedDict()
    for cat in CATEGORY_ORDER:
        out[cat] = []
    for cmd, (cat, uc) in CATALOG.items():
        out.setdefault(cat, []).append((cmd, uc))
    # drop empty categories
    return OrderedDict((k, v) for k, v in out.items() if v)


def total_documented() -> int:
    return len(CATALOG)
